Server:
  Port: "8085"
  IP: "127.0.0.1"
  Url: "https://skisiel.com"

Paths:
  Static: "../githttp/static"
  Templates: "./templates"
  Media: "./media"

Contact:
  Name: "Sophie Kisiel"
  Email: "sophie@skisiel.com"
